/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework_manager;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author doilhan
 */
public class DlgAddEdit extends javax.swing.JDialog {
    boolean cancelled = false;
    String priority;
    String month;
    String day;
    String year;
    Date time;
    
    
    public DlgAddEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    String[] getFieldValues() {
        String[] values = new String[5];
        values[0] = txtTitle.getText();
        values[1] = txtDescription.getText();
        values[2] = priority;
        if(month == null){
            month = "Jan";
        }
        if(day == null){
            day = "1";
        }
        if(year == null){
            year = "2018";
        }
        values[3] = month+","+day+","+year;
        System.out.println(Arrays.toString(values[3].split(",")));
        time = (Date) SpinnerTime.getValue();
        DateFormat dateformat = new SimpleDateFormat("hh:mm a");
        values[4] = dateformat.format(time);
        return values;
    }
    
    
    void setFieldValues(String[] values) {
        txtTitle.setText(values[0]);
        txtDescription.setText(values[1]);
        if("High".equals(values[2])){
            highradiobtn.setSelected(true);
        }else if("Medium".equals(values[2])){
            mediumradiobtn.setSelected(true);
        }else if("Low".equals(values[2])){
            lowradiobtn.setSelected(true);
        }
        String[] date = values[3].split(",");
           for (int i = 0; i < MonthCombo.getItemCount(); i++)
        {
            if(MonthCombo.getItemAt(i).equals(date[0])){
                MonthCombo.setSelectedIndex(i);
            }
        }
           for (int i = 0; i < DaysCombo.getItemCount(); i++)
        {
            if(DaysCombo.getItemAt(i).equals(date[1])){
                DaysCombo.setSelectedIndex(i);
            }
        }
           for (int i = 0; i < YrCombo.getItemCount(); i++)
        {
            if(YrCombo.getItemAt(i).equals(date[1])){
                YrCombo.setSelectedIndex(i);
            }
        }
    
        
       Date times = null;
        try {
            times = new SimpleDateFormat("hh:mm a").parse(values[4]);
        } catch (ParseException ex) {
            Logger.getLogger(DlgAddEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
       SpinnerTime.setValue(times);
        
    }
    boolean wascancelled(){
        return cancelled;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadiobtnGroup = new javax.swing.ButtonGroup();
        okbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labeltitle = new javax.swing.JLabel();
        labeldescription = new javax.swing.JLabel();
        txtPriority = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        highradiobtn = new javax.swing.JRadioButton();
        mediumradiobtn = new javax.swing.JRadioButton();
        lowradiobtn = new javax.swing.JRadioButton();
        txtDeadline = new javax.swing.JLabel();
        MonthCombo = new javax.swing.JComboBox<>();
        DaysCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        YrCombo = new javax.swing.JComboBox<>();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        SpinnerTime = new javax.swing.JSpinner(sm);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okbtn.setText("Ok");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Homework Details :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Silom", 0, 13))); // NOI18N

        labeltitle.setFont(new java.awt.Font("Silom", 0, 12)); // NOI18N
        labeltitle.setText("Title");

        labeldescription.setFont(new java.awt.Font("Silom", 0, 12)); // NOI18N
        labeldescription.setText("Description");

        txtPriority.setFont(new java.awt.Font("Silom", 0, 12)); // NOI18N
        txtPriority.setText("Priority : ");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        RadiobtnGroup.add(highradiobtn);
        highradiobtn.setText("High");
        highradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highradiobtnActionPerformed(evt);
            }
        });

        RadiobtnGroup.add(mediumradiobtn);
        mediumradiobtn.setText("Medium");
        mediumradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumradiobtnActionPerformed(evt);
            }
        });

        RadiobtnGroup.add(lowradiobtn);
        lowradiobtn.setText("Low");
        lowradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowradiobtnActionPerformed(evt);
            }
        });

        txtDeadline.setFont(new java.awt.Font("Silom", 0, 12)); // NOI18N
        txtDeadline.setText("Deadline");

        MonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        MonthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthComboActionPerformed(evt);
            }
        });

        DaysCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DaysCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaysComboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Silom", 0, 12)); // NOI18N
        jLabel2.setText("Date :");

        jLabel3.setFont(new java.awt.Font("Silom", 0, 12)); // NOI18N
        jLabel3.setText("Time :");

        YrCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        YrCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YrComboActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(SpinnerTime, "HH:mm a");
        SpinnerTime.setEditor(de);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtTitle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeldescription)
                            .addComponent(labeltitle)
                            .addComponent(txtDeadline)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(SpinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(12, 12, 12)
                                    .addComponent(MonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DaysCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(YrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtPriority)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lowradiobtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mediumradiobtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(highradiobtn))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labeltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeldescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriority)
                    .addComponent(highradiobtn)
                    .addComponent(mediumradiobtn)
                    .addComponent(lowradiobtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DaysCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SpinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(cancelbtn)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okbtn)
                    .addComponent(cancelbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        this.cancelled = true;
        this.dispose();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_okbtnActionPerformed

    private void MonthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthComboActionPerformed
        // TODO add your handling code here:
        month = (String) MonthCombo.getSelectedItem();
    }//GEN-LAST:event_MonthComboActionPerformed

    private void lowradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowradiobtnActionPerformed
        // TODO add your handling code here:
        priority = "Low";
        
    }//GEN-LAST:event_lowradiobtnActionPerformed

    private void mediumradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumradiobtnActionPerformed
        // TODO add your handling code here:
        priority = "Medium";
    }//GEN-LAST:event_mediumradiobtnActionPerformed

    private void highradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highradiobtnActionPerformed
        // TODO add your handling code here:
        priority = "High";
    }//GEN-LAST:event_highradiobtnActionPerformed

    private void DaysComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaysComboActionPerformed
        // TODO add your handling code here:
        day = (String) DaysCombo.getSelectedItem();
    }//GEN-LAST:event_DaysComboActionPerformed

    private void YrComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YrComboActionPerformed
        // TODO add your handling code here:
        year = (String) YrCombo.getSelectedItem();
    }//GEN-LAST:event_YrComboActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DaysCombo;
    private javax.swing.JComboBox<String> MonthCombo;
    private javax.swing.ButtonGroup RadiobtnGroup;
    private javax.swing.JSpinner SpinnerTime;
    private javax.swing.JComboBox<String> YrCombo;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JRadioButton highradiobtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeldescription;
    private javax.swing.JLabel labeltitle;
    private javax.swing.JRadioButton lowradiobtn;
    private javax.swing.JRadioButton mediumradiobtn;
    private javax.swing.JButton okbtn;
    private javax.swing.JLabel txtDeadline;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JLabel txtPriority;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
