/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework_manager;

import java.awt.Toolkit;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;

/**
 *
 * @author doilhan
 */
public class TimerViewController extends javax.swing.JDialog {
    TimerSetup timersetup;
    int[] setup = new int[3];
    int inseconds;
    Timer timer = new Timer();
    boolean ran1st = true;
    Alarm alarm;

    /**
     * Creates new form TimerViewController
     */
    public TimerViewController(java.awt.Frame parent, boolean modal, Model model, TimerSetup timersetup) {
        super(parent, modal);
        try {
            alarm = new Alarm();
        } catch (IOException ex) {
            Logger.getLogger(TimerViewController.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.timersetup = timersetup;
        lbtask.setText(timersetup.taskWorkingon);
        setup = timersetup.getTimeintInt();
        lbhour.setText(String.format("%02d", setup[0]));
        lbminute.setText(String.format("%02d",setup[1]));
        lbseconds.setText(String.format("%02d", setup[2]));
        inseconds = inseconds();
        
        
    }
    void reset(){
        int[] resettime = new int[3];
        resettime = timersetup.getTimeintInt();
        lbhour.setText(String.format("%02d", resettime[0]));
        lbminute.setText(String.format("%02d", resettime[1]));
        lbseconds.setText(String.format("%02d", resettime[2]));
        
    }
    int inseconds(){
        inseconds = setup[0]*60*60+setup[1]*60+setup[2];
        return inseconds;
    }
    
    void setformat(){
        long hours = (inseconds/3600);
        long minutes = (inseconds/60)%60;
        long seconds = inseconds%60;
        lbhour.setText(String.format("%02d", hours));
        lbminute.setText(String.format("%02d", minutes));
        lbseconds.setText(String.format("%02d", seconds));
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbminute = new javax.swing.JLabel();
        lbseconds = new javax.swing.JLabel();
        lbsetup3 = new javax.swing.JLabel();
        lbhour = new javax.swing.JLabel();
        lbsetup2 = new javax.swing.JLabel();
        btnstart = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTaskWorkingOn = new javax.swing.JLabel();
        taskcompletedbtn = new javax.swing.JButton();
        lbtask = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setForeground(new java.awt.Color(153, 255, 255));

        lbminute.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbminute.setText("00");

        lbseconds.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbseconds.setText("00");

        lbsetup3.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbsetup3.setText(":");

        lbhour.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbhour.setText("00");

        lbsetup2.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lbsetup2.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lbhour)
                .addGap(18, 18, 18)
                .addComponent(lbsetup2)
                .addGap(18, 18, 18)
                .addComponent(lbminute)
                .addGap(18, 18, 18)
                .addComponent(lbsetup3)
                .addGap(18, 18, 18)
                .addComponent(lbseconds)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbhour)
                    .addComponent(lbsetup2)
                    .addComponent(lbminute)
                    .addComponent(lbsetup3)
                    .addComponent(lbseconds, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnstart.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnstart.setText("Start");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        jLabel1.setText("Task Working On");

        txtTaskWorkingOn.setFont(new java.awt.Font("Silom", 0, 12)); // NOI18N
        txtTaskWorkingOn.setText(" ");

        taskcompletedbtn.setText("Task Completed");
        taskcompletedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskcompletedbtnActionPerformed(evt);
            }
        });

        lbtask.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbtask.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbtask, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTaskWorkingOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taskcompletedbtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(taskcompletedbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtTaskWorkingOn))
                    .addComponent(lbtask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
        // TODO add your handling code here:
        TimerTask task = null;
        if(btnstart.getText()=="Start"){
        task = new TimerTask(){
            public void run() {
                
                inseconds--;
                setformat();
                if(inseconds == 0){
                    timer.cancel();
                    alarm.play();
                    btnstart.setText("Ok");
                    
                } 
                
            }
        };
            //when starting
        timer.scheduleAtFixedRate(task, 0, 1000);
        btnstart.setText("Stop");
        } else if(btnstart.getText()=="Stop"){
            inseconds = inseconds;
            if(inseconds != 0){
            timer.cancel();
            timer.purge();
            btnstart.setText("Resume");
            }
        } else if(btnstart.getText() == "Resume"){
            this.timer = new Timer();
            task = new TimerTask(){
                public void run(){
                    inseconds--;
                    setformat();
                    if(inseconds == 0){
                        timer.cancel();
                        alarm.play();
                        btnstart.setText("Ok");
                    }
                }
            };
            this.timer.schedule(task, 0, 1000);
            btnstart.setText("Stop");
        } else if(btnstart.getText()=="Ok"){
            alarm.stop();
        }
        
        
    }//GEN-LAST:event_btnstartActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        alarm.stop();
        timer.cancel();
        timer.purge();
        this.timer = new Timer();
        inseconds = inseconds();
        btnstart.setText("Start");
        reset();
    }//GEN-LAST:event_btnclearActionPerformed

    private void taskcompletedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskcompletedbtnActionPerformed
        // TODO add your handling code here:
        timer.cancel();
        timer.purge();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_taskcompletedbtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbhour;
    private javax.swing.JLabel lbminute;
    private javax.swing.JLabel lbseconds;
    private javax.swing.JLabel lbsetup2;
    private javax.swing.JLabel lbsetup3;
    private javax.swing.JLabel lbtask;
    private javax.swing.JButton taskcompletedbtn;
    private javax.swing.JLabel txtTaskWorkingOn;
    // End of variables declaration//GEN-END:variables
}
