/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework_manager;

/**
 *
 * @author doilhan
 */
public class TimerSetup extends javax.swing.JDialog {
    Model model;
    int taskCount;
    String [] tasks;
    boolean wasCancelled = false;
    java.awt.Frame viewcontroller;
    String taskWorkingon;
    /**
     * Creates new form TimerSetup
     */
    public TimerSetup(java.awt.Frame parent, boolean modal, Model model) {
        super(parent, modal);
        viewcontroller = parent;
        initComponents();
        this.model = model;
        taskCount = model.taskCount;
        tasks = model.getTasks();
        for(int i = 0; i< taskCount;i++){
            taskcombo.addItem(tasks[i]);
        }
        if(taskcombo.getItemCount()== 0){
            taskcombo.addItem("No tasks available");
        }
    }
    int[] getTimeintInt(){
        int[] timelimit = new int[3];
        timelimit[0] = (int) Spinnerhr.getValue();
        timelimit[1] = (int) Spinnermin.getValue();
        timelimit[2] = (int) Spinnersec.getValue();
    
        return timelimit;
    }
    String[] getTime(){
        String[] timelimit = new String[3];
        timelimit[0] = Integer.toString((int) Spinnerhr.getValue());
        timelimit[1] = Integer.toString((int) Spinnermin.getValue());
        timelimit[2] = Integer.toString((int) Spinnersec.getValue());
    
        return timelimit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTaskWorking = new javax.swing.JLabel();
        taskcombo = new javax.swing.JComboBox<>();
        txtTaskWorking1 = new javax.swing.JLabel();
        Spinnermin = new javax.swing.JSpinner();
        Spinnerhr = new javax.swing.JSpinner();
        Spinnersec = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCancel = new javax.swing.JButton();
        setupbtn1 = new javax.swing.JButton();
        lbstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtTaskWorking.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        txtTaskWorking.setText("What task are you working on?");

        taskcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskcomboActionPerformed(evt);
            }
        });

        txtTaskWorking1.setFont(new java.awt.Font("Silom", 0, 13)); // NOI18N
        txtTaskWorking1.setText("For how long?");

        Spinnermin.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Spinnermin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        Spinnerhr.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Spinnerhr.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        Spinnersec.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Spinnersec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel1.setText("Hours");

        jLabel2.setText("Minute");

        jLabel3.setText("Second");

        txtCancel.setText("Cancel");
        txtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelActionPerformed(evt);
            }
        });

        setupbtn1.setText("Set");
        setupbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupbtn1ActionPerformed(evt);
            }
        });

        lbstatus.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTaskWorking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTaskWorking1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(setupbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Spinnerhr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Spinnermin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(Spinnersec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(taskcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTaskWorking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTaskWorking1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spinnerhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinnermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinnersec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setupbtn1)
                    .addComponent(txtCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupbtn1ActionPerformed
        // TODO add your handling code here:
        if(taskWorkingon == "No tasks available"){
        lbstatus.setText("Please select a task");
        } else{
        TimerViewController timing = new TimerViewController(viewcontroller, true, model, this);
        this.setVisible(false);
        timing.setVisible(true);
        this.dispose();}
    }//GEN-LAST:event_setupbtn1ActionPerformed

    private void txtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelActionPerformed
        // TODO add your handling code here:
        wasCancelled = true;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_txtCancelActionPerformed

    private void taskcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskcomboActionPerformed
        // TODO add your handling code here:
        taskWorkingon = (String) taskcombo.getSelectedItem();
    }//GEN-LAST:event_taskcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spinnerhr;
    private javax.swing.JSpinner Spinnermin;
    private javax.swing.JSpinner Spinnersec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbstatus;
    private javax.swing.JButton setupbtn1;
    private javax.swing.JComboBox<String> taskcombo;
    private javax.swing.JButton txtCancel;
    private javax.swing.JLabel txtTaskWorking;
    private javax.swing.JLabel txtTaskWorking1;
    // End of variables declaration//GEN-END:variables
}
